apiVersion: 1

datasources:
  # Prometheus - Main metrics datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST
      queryTimeout: 60s
      cacheLevel: High
      incrementalQuerying: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
    version: 1

  # Loki - Log aggregation datasource
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 5000
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: "container_name=(\\w+)"
          name: Container
          url: "/d/container-metrics?var-container=$${__value.raw}"
    version: 1

  # PostgreSQL - Markets Database
  - name: PostgreSQL-Markets
    type: postgres
    access: proxy
    url: markets_db:5432
    database: openbb_data
    user: openbb
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${MARKETS_DB_PASSWORD:-openbb}
    version: 1

  # PostgreSQL - Data Warehouse
  - name: PostgreSQL-Warehouse
    type: postgres
    access: proxy
    url: data-warehouse_postgres_1:5432
    database: postgres
    user: postgres
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    secureJsonData:
      password: ${WAREHOUSE_DB_PASSWORD:-postgres}
    version: 1
